language: node_js
node_js:
  - '12'
dist: trusty
cache:
  directories:
    - node_modules
script:
  - npm run test
deploy:
  provider: heroku
  api_key:
    secure: 'f013b7ea-83fc-4496-92e4-e42379501106'
  app: sheltered-dawn-47902
