language: node_js
node_js:
  - '12'
dist: trusty
cache:
  directories:
    - node_modules
script:
  - npm run test
deploy:
  provider: heroku
  api_key:
    secure: $APIACCESS
  app: sheltered-dawn-47902
  on:
    branch: master
