language: node_js
node_js:
  - '12'
dist: trusty
cache:
  directories:
    - node_modules
script:
  - npm run test
deploy:
  provider: heroku
  api_key: 22118f53-8504-4aaa-95d1-d38e938bc5b9
  app: sheltered-dawn-47902
